# Generated by Django 5.0 on 2025-12-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
