# Generated by Django 5.0 on 2025-12-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_offer_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='valid_until',
            field=models.DateField(),
        ),
    ]
