# Generated by Django 5.0 on 2025-12-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_offer_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(help_text='Price in whole currency units (e.g. rupees)')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
