# Generated by Django 5.1.7 on 2025-12-23 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this time slot')),
                ('start_time', models.TimeField(help_text='Start time (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 09:30)')),
                ('is_available', models.BooleanField(default=True, help_text='True if slot is available, False if busy/blocked')),
                ('is_blocked', models.BooleanField(default=False, help_text='True if owner manually blocked this slot')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this slot', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'start_time'], name='store_times_date_62bb85_idx')],
                'unique_together': {('date', 'start_time', 'end_time')},
            },
        ),
    ]
