# Generated by Django 5.1.7 on 2025-12-29 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('staff_count', models.PositiveIntegerField(default=1, help_text='Number of available staff for this month')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
