# Generated by Django 5.1.7 on 2026-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_add_staff_assignment_and_fix_blockedslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveIndex(
            model_name='blockedslot',
            name='store_block_start_t_11cf37_idx',
        ),
        # StaffAvailability unique_together was on (year,month,day) removed in 0009; skip AlterUniqueTogether to avoid FieldDoesNotExist
        migrations.AlterField(
            model_name='staffavailability',
            name='staff_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of available staff for this date'),
        ),
        migrations.AddIndex(
            model_name='blockedslot',
            index=models.Index(fields=['date', 'start_time'], name='store_block_date_921274_idx'),
        ),
    ]
