# Generated by Django 5.0 on 2025-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
