# Generated by Django 5.0 on 2025-12-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_partner_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
