# Generated by Django 5.0 on 2025-12-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partner_is_verified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partner',
            new_name='PartnerModel',
        ),
    ]
