# Generated by Django 5.0 on 2025-12-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
