# Generated by Django 5.0 on 2025-12-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_partner_created_at_alter_partner_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
