# Generated by Django 5.0 on 2025-12-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
